### ISSUE TITLE
cargo contract build 

### ISSUE THREAD

**Issue by polblancoo** [swanky-dapps/dex#5] opened 2022-12-18 02:04 UTC
cargo_contract::crate_metadata: Fetching cargo metadata for Cargo.toml
ERROR: Cannot infer the root project id

**Comment by HyunggyuJang** [comment] 2023-01-12 08:30
Duplicate of #3. To compile all contracts, use
```sh
yarn compile
```

**Closed as completed by HyunggyuJang** 2023-01-12 08:30 UTC
